from flask import Flask, request, jsonify, render_template
from datetime import datetime, timedelta
import pickle
import numpy as np

app = Flask(__name__, template_folder='templates', static_folder='static', static_url_path='/static')

# Load ML Model
model = pickle.load(open("model.pkl", "rb"))

# Sample Case Data
sample_cases = [
{'id': 'C1000', 'type': 'Civil', 'age': 3.47, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1001', 'type': 'Civil', 'age': 3.57, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1002', 'type': 'Criminal', 'age': 3.18, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1003', 'type': 'Family', 'age': 4.02, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1004', 'type': 'Property', 'age': 4.53, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1005', 'type': 'Property', 'age': 4.58, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1006', 'type': 'Property', 'age': 3.02, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1007', 'type': 'Criminal', 'age': 1.74, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1008', 'type': 'Corporate', 'age': 2.56, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1009', 'type': 'Property', 'age': 4.16, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1010', 'type': 'Family', 'age': 2.4, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1011', 'type': 'Corporate', 'age': 1.96, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1012', 'type': 'Criminal', 'age': 4.29, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1013', 'type': 'Property', 'age': 3.65, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1014', 'type': 'Civil', 'age': 1.35, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1015', 'type': 'Family', 'age': 0.74, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1016', 'type': 'Family', 'age': 1.41, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1017', 'type': 'Property', 'age': 1.21, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1018', 'type': 'Civil', 'age': 0.53, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1019', 'type': 'Property', 'age': 4.26, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1020', 'type': 'Criminal', 'age': 2.36, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1021', 'type': 'Civil', 'age': 4.29, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1022', 'type': 'Family', 'age': 0.66, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1023', 'type': 'Criminal', 'age': 0.78, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1024', 'type': 'Civil', 'age': 1.11, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1025', 'type': 'Property', 'age': 4.03, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1026', 'type': 'Family', 'age': 1.41, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1027', 'type': 'Family', 'age': 1.86, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1028', 'type': 'Civil', 'age': 3.09, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1029', 'type': 'Corporate', 'age': 0.71, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1030', 'type': 'Criminal', 'age': 2.39, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1031', 'type': 'Property', 'age': 2.11, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1032', 'type': 'Civil', 'age': 3.0, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1033', 'type': 'Civil', 'age': 4.39, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1034', 'type': 'Family', 'age': 3.81, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1035', 'type': 'Corporate', 'age': 0.92, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1036', 'type': 'Property', 'age': 4.29, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1037', 'type': 'Property', 'age': 4.33, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1038', 'type': 'Family', 'age': 2.42, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1039', 'type': 'Corporate', 'age': 1.37, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1040', 'type': 'Civil', 'age': 2.67, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1041', 'type': 'Criminal', 'age': 0.86, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1042', 'type': 'Civil', 'age': 4.82, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1043', 'type': 'Civil', 'age': 3.36, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1044', 'type': 'Family', 'age': 4.05, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1045', 'type': 'Civil', 'age': 2.29, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1046', 'type': 'Criminal', 'age': 1.6, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1047', 'type': 'Criminal', 'age': 1.63, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1048', 'type': 'Family', 'age': 3.83, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1049', 'type': 'Property', 'age': 2.54, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1050', 'type': 'Civil', 'age': 2.32, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1051', 'type': 'Criminal', 'age': 3.43, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1052', 'type': 'Corporate', 'age': 1.0, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1053', 'type': 'Corporate', 'age': 0.63, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1054', 'type': 'Family', 'age': 2.2, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1055', 'type': 'Civil', 'age': 1.95, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1056', 'type': 'Civil', 'age': 3.3, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1057', 'type': 'Property', 'age': 2.99, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1058', 'type': 'Civil', 'age': 3.25, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1059', 'type': 'Civil', 'age': 2.79, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1060', 'type': 'Corporate', 'age': 4.4, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1061', 'type': 'Civil', 'age': 1.28, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1062', 'type': 'Property', 'age': 0.76, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1063', 'type': 'Civil', 'age': 3.04, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1064', 'type': 'Family', 'age': 2.25, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1065', 'type': 'Corporate', 'age': 4.16, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1066', 'type': 'Corporate', 'age': 4.63, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1067', 'type': 'Criminal', 'age': 1.45, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1068', 'type': 'Criminal', 'age': 4.62, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1069', 'type': 'Criminal', 'age': 2.09, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1070', 'type': 'Civil', 'age': 2.92, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1071', 'type': 'Civil', 'age': 2.76, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1072', 'type': 'Family', 'age': 4.19, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1073', 'type': 'Family', 'age': 4.19, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1074', 'type': 'Criminal', 'age': 3.74, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1075', 'type': 'Civil', 'age': 0.87, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1076', 'type': 'Civil', 'age': 2.2, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1077', 'type': 'Corporate', 'age': 4.46, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1078', 'type': 'Civil', 'age': 3.06, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1079', 'type': 'Family', 'age': 2.19, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1080', 'type': 'Corporate', 'age': 3.1, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1081', 'type': 'Corporate', 'age': 1.21, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1082', 'type': 'Corporate', 'age': 4.96, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1083', 'type': 'Criminal', 'age': 4.8, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1084', 'type': 'Family', 'age': 3.37, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1085', 'type': 'Property', 'age': 2.41, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1086', 'type': 'Family', 'age': 3.3, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1087', 'type': 'Family', 'age': 1.94, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1088', 'type': 'Property', 'age': 1.82, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1089', 'type': 'Family', 'age': 1.98, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1090', 'type': 'Civil', 'age': 3.88, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1091', 'type': 'Corporate', 'age': 0.95, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1092', 'type': 'Criminal', 'age': 3.21, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1093', 'type': 'Civil', 'age': 2.06, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1094', 'type': 'Family', 'age': 1.55, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1095', 'type': 'Civil', 'age': 3.34, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1096', 'type': 'Criminal', 'age': 1.24, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1097', 'type': 'Corporate', 'age': 0.84, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1098', 'type': 'Civil', 'age': 1.98, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1099', 'type': 'Criminal', 'age': 0.83, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1100', 'type': 'Family', 'age': 4.03, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1101', 'type': 'Family', 'age': 0.83, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1102', 'type': 'Civil', 'age': 1.45, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1103', 'type': 'Criminal', 'age': 3.2, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1104', 'type': 'Property', 'age': 2.66, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1105', 'type': 'Civil', 'age': 2.77, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1106', 'type': 'Family', 'age': 3.17, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1107', 'type': 'Corporate', 'age': 2.95, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1108', 'type': 'Civil', 'age': 2.2, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1109', 'type': 'Family', 'age': 2.21, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1110', 'type': 'Family', 'age': 1.4, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1111', 'type': 'Property', 'age': 1.57, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1112', 'type': 'Corporate', 'age': 4.51, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1113', 'type': 'Property', 'age': 4.89, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1114', 'type': 'Corporate', 'age': 4.12, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1115', 'type': 'Corporate', 'age': 1.38, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1116', 'type': 'Family', 'age': 1.26, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1117', 'type': 'Corporate', 'age': 1.35, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1118', 'type': 'Corporate', 'age': 2.71, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1119', 'type': 'Property', 'age': 3.87, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1120', 'type': 'Family', 'age': 2.6, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1121', 'type': 'Corporate', 'age': 1.2, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1122', 'type': 'Criminal', 'age': 2.32, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1123', 'type': 'Property', 'age': 2.89, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1124', 'type': 'Civil', 'age': 3.08, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1125', 'type': 'Criminal', 'age': 1.03, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1126', 'type': 'Criminal', 'age': 3.03, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1127', 'type': 'Family', 'age': 1.98, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1128', 'type': 'Family', 'age': 0.91, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1129', 'type': 'Criminal', 'age': 4.52, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1130', 'type': 'Family', 'age': 2.42, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1131', 'type': 'Criminal', 'age': 1.95, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1132', 'type': 'Property', 'age': 3.34, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1133', 'type': 'Family', 'age': 2.25, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1134', 'type': 'Property', 'age': 4.79, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1135', 'type': 'Corporate', 'age': 1.02, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1136', 'type': 'Family', 'age': 0.76, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1137', 'type': 'Civil', 'age': 1.16, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1138', 'type': 'Property', 'age': 2.0, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1139', 'type': 'Property', 'age': 1.58, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1140', 'type': 'Criminal', 'age': 3.75, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1141', 'type': 'Criminal', 'age': 3.27, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1142', 'type': 'Civil', 'age': 1.51, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1143', 'type': 'Civil', 'age': 1.23, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1144', 'type': 'Property', 'age': 3.81, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1145', 'type': 'Family', 'age': 4.54, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1146', 'type': 'Family', 'age': 2.78, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1147', 'type': 'Criminal', 'age': 2.05, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1148', 'type': 'Family', 'age': 3.9, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1149', 'type': 'Civil', 'age': 1.31, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1150', 'type': 'Criminal', 'age': 3.12, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1151', 'type': 'Criminal', 'age': 3.32, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1152', 'type': 'Corporate', 'age': 1.89, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1153', 'type': 'Criminal', 'age': 4.01, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1154', 'type': 'Family', 'age': 1.02, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1155', 'type': 'Corporate', 'age': 4.61, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1156', 'type': 'Criminal', 'age': 4.16, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1157', 'type': 'Civil', 'age': 2.51, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1158', 'type': 'Family', 'age': 4.56, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1159', 'type': 'Property', 'age': 4.47, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1160', 'type': 'Criminal', 'age': 3.51, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1161', 'type': 'Family', 'age': 2.85, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1162', 'type': 'Corporate', 'age': 0.94, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1163', 'type': 'Criminal', 'age': 2.97, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1164', 'type': 'Family', 'age': 3.76, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1165', 'type': 'Property', 'age': 2.38, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1166', 'type': 'Family', 'age': 2.82, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1167', 'type': 'Corporate', 'age': 4.5, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1168', 'type': 'Criminal', 'age': 2.23, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1169', 'type': 'Civil', 'age': 3.06, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1170', 'type': 'Civil', 'age': 1.99, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1171', 'type': 'Property', 'age': 1.41, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1172', 'type': 'Criminal', 'age': 2.8, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1173', 'type': 'Criminal', 'age': 1.66, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1174', 'type': 'Civil', 'age': 4.22, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1175', 'type': 'Family', 'age': 4.69, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1176', 'type': 'Corporate', 'age': 3.56, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1177', 'type': 'Criminal', 'age': 2.5, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1178', 'type': 'Property', 'age': 3.01, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1179', 'type': 'Corporate', 'age': 4.36, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1180', 'type': 'Property', 'age': 1.66, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1181', 'type': 'Property', 'age': 4.29, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1182', 'type': 'Civil', 'age': 3.39, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1183', 'type': 'Property', 'age': 2.19, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1184', 'type': 'Civil', 'age': 2.77, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1185', 'type': 'Corporate', 'age': 4.59, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1186', 'type': 'Criminal', 'age': 4.2, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1187', 'type': 'Civil', 'age': 3.96, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1188', 'type': 'Criminal', 'age': 4.05, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1189', 'type': 'Property', 'age': 2.45, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1190', 'type': 'Property', 'age': 3.76, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1191', 'type': 'Property', 'age': 1.7, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1192', 'type': 'Property', 'age': 1.37, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1193', 'type': 'Criminal', 'age': 2.86, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1194', 'type': 'Family', 'age': 2.05, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1195', 'type': 'Corporate', 'age': 2.28, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1196', 'type': 'Civil', 'age': 2.27, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1197', 'type': 'Family', 'age': 1.73, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1198', 'type': 'Criminal', 'age': 1.99, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1199', 'type': 'Family', 'age': 0.76, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1200', 'type': 'Criminal', 'age': 3.93, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1201', 'type': 'Criminal', 'age': 4.37, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1202', 'type': 'Property', 'age': 3.99, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1203', 'type': 'Criminal', 'age': 4.85, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1204', 'type': 'Criminal', 'age': 3.76, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1205', 'type': 'Property', 'age': 4.93, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1206', 'type': 'Property', 'age': 1.91, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1207', 'type': 'Family', 'age': 4.43, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1208', 'type': 'Family', 'age': 2.42, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1209', 'type': 'Civil', 'age': 3.25, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1210', 'type': 'Property', 'age': 3.62, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1211', 'type': 'Civil', 'age': 4.29, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1212', 'type': 'Criminal', 'age': 1.96, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1213', 'type': 'Property', 'age': 0.92, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1214', 'type': 'Civil', 'age': 4.3, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1215', 'type': 'Civil', 'age': 2.75, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1216', 'type': 'Civil', 'age': 4.59, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1217', 'type': 'Family', 'age': 4.02, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1218', 'type': 'Family', 'age': 4.03, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1219', 'type': 'Property', 'age': 2.24, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1220', 'type': 'Civil', 'age': 3.66, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1221', 'type': 'Family', 'age': 4.61, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1222', 'type': 'Civil', 'age': 1.51, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1223', 'type': 'Family', 'age': 2.05, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1224', 'type': 'Property', 'age': 4.0, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1225', 'type': 'Civil', 'age': 0.63, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1226', 'type': 'Corporate', 'age': 1.99, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1227', 'type': 'Criminal', 'age': 2.9, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1228', 'type': 'Corporate', 'age': 4.34, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1229', 'type': 'Family', 'age': 0.74, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1230', 'type': 'Family', 'age': 4.57, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1231', 'type': 'Civil', 'age': 0.94, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1232', 'type': 'Property', 'age': 3.48, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1233', 'type': 'Family', 'age': 1.13, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1234', 'type': 'Family', 'age': 1.46, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1235', 'type': 'Corporate', 'age': 4.65, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1236', 'type': 'Civil', 'age': 0.79, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1237', 'type': 'Property', 'age': 2.56, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1238', 'type': 'Family', 'age': 4.55, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1239', 'type': 'Corporate', 'age': 3.85, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1240', 'type': 'Criminal', 'age': 1.13, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1241', 'type': 'Civil', 'age': 3.13, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1242', 'type': 'Corporate', 'age': 2.68, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1243', 'type': 'Civil', 'age': 4.51, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1244', 'type': 'Family', 'age': 0.59, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1245', 'type': 'Family', 'age': 1.57, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1246', 'type': 'Property', 'age': 4.94, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1247', 'type': 'Family', 'age': 4.95, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1248', 'type': 'Corporate', 'age': 2.37, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1249', 'type': 'Criminal', 'age': 4.29, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1250', 'type': 'Civil', 'age': 4.07, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1251', 'type': 'Property', 'age': 0.65, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1252', 'type': 'Civil', 'age': 0.84, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1253', 'type': 'Civil', 'age': 3.14, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1254', 'type': 'Criminal', 'age': 2.75, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1255', 'type': 'Criminal', 'age': 2.74, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1256', 'type': 'Civil', 'age': 2.85, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1257', 'type': 'Civil', 'age': 4.05, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1258', 'type': 'Family', 'age': 2.53, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1259', 'type': 'Criminal', 'age': 2.03, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1260', 'type': 'Family', 'age': 2.38, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1261', 'type': 'Property', 'age': 3.93, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1262', 'type': 'Family', 'age': 3.96, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1263', 'type': 'Civil', 'age': 4.72, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1264', 'type': 'Criminal', 'age': 4.1, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1265', 'type': 'Family', 'age': 3.54, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1266', 'type': 'Property', 'age': 1.78, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1267', 'type': 'Corporate', 'age': 2.67, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1268', 'type': 'Criminal', 'age': 1.18, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1269', 'type': 'Family', 'age': 3.39, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1270', 'type': 'Criminal', 'age': 3.61, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1271', 'type': 'Corporate', 'age': 3.77, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1272', 'type': 'Family', 'age': 2.4, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1273', 'type': 'Corporate', 'age': 1.87, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1274', 'type': 'Family', 'age': 4.62, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1275', 'type': 'Corporate', 'age': 2.93, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1276', 'type': 'Corporate', 'age': 2.82, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1277', 'type': 'Criminal', 'age': 3.54, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1278', 'type': 'Civil', 'age': 4.89, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1279', 'type': 'Civil', 'age': 3.31, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1280', 'type': 'Property', 'age': 4.46, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1281', 'type': 'Criminal', 'age': 0.91, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1282', 'type': 'Corporate', 'age': 1.65, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1283', 'type': 'Corporate', 'age': 3.59, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1284', 'type': 'Civil', 'age': 1.55, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1285', 'type': 'Property', 'age': 0.52, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1286', 'type': 'Property', 'age': 2.05, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1287', 'type': 'Criminal', 'age': 2.68, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1288', 'type': 'Corporate', 'age': 2.67, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1289', 'type': 'Corporate', 'age': 1.4, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1290', 'type': 'Corporate', 'age': 4.39, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1291', 'type': 'Property', 'age': 3.96, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1292', 'type': 'Property', 'age': 2.97, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1293', 'type': 'Criminal', 'age': 0.67, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1294', 'type': 'Civil', 'age': 1.96, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1295', 'type': 'Family', 'age': 1.92, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1296', 'type': 'Corporate', 'age': 0.89, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1297', 'type': 'Property', 'age': 1.16, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1298', 'type': 'Civil', 'age': 4.94, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1299', 'type': 'Corporate', 'age': 2.34, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1300', 'type': 'Corporate', 'age': 2.13, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1301', 'type': 'Criminal', 'age': 2.48, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1302', 'type': 'Corporate', 'age': 0.63, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1303', 'type': 'Criminal', 'age': 1.37, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1304', 'type': 'Property', 'age': 1.06, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1305', 'type': 'Family', 'age': 1.72, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1306', 'type': 'Property', 'age': 4.6, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1307', 'type': 'Property', 'age': 1.43, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1308', 'type': 'Family', 'age': 2.87, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1309', 'type': 'Criminal', 'age': 2.17, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1310', 'type': 'Property', 'age': 4.44, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1311', 'type': 'Corporate', 'age': 2.15, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1312', 'type': 'Criminal', 'age': 4.36, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1313', 'type': 'Civil', 'age': 1.63, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1314', 'type': 'Corporate', 'age': 3.22, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1315', 'type': 'Civil', 'age': 2.14, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1316', 'type': 'Corporate', 'age': 4.45, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1317', 'type': 'Property', 'age': 2.01, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1318', 'type': 'Family', 'age': 2.35, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1319', 'type': 'Property', 'age': 0.95, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1320', 'type': 'Civil', 'age': 4.31, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1321', 'type': 'Civil', 'age': 1.23, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1322', 'type': 'Family', 'age': 2.28, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1323', 'type': 'Civil', 'age': 4.02, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1324', 'type': 'Criminal', 'age': 4.82, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1325', 'type': 'Civil', 'age': 3.17, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1326', 'type': 'Criminal', 'age': 1.86, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1327', 'type': 'Corporate', 'age': 1.02, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1328', 'type': 'Family', 'age': 1.96, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1329', 'type': 'Corporate', 'age': 2.26, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1330', 'type': 'Criminal', 'age': 3.37, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1331', 'type': 'Civil', 'age': 4.86, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1332', 'type': 'Criminal', 'age': 4.92, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1333', 'type': 'Property', 'age': 4.19, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1334', 'type': 'Civil', 'age': 1.85, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1335', 'type': 'Family', 'age': 3.59, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1336', 'type': 'Property', 'age': 1.16, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1337', 'type': 'Family', 'age': 3.13, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1338', 'type': 'Criminal', 'age': 2.65, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1339', 'type': 'Criminal', 'age': 4.97, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1340', 'type': 'Property', 'age': 2.92, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1341', 'type': 'Family', 'age': 1.08, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1342', 'type': 'Family', 'age': 1.87, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1343', 'type': 'Property', 'age': 0.65, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1344', 'type': 'Civil', 'age': 4.62, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1345', 'type': 'Corporate', 'age': 1.87, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1346', 'type': 'Family', 'age': 0.86, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1347', 'type': 'Criminal', 'age': 4.3, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1348', 'type': 'Property', 'age': 4.5, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1349', 'type': 'Family', 'age': 3.53, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1350', 'type': 'Corporate', 'age': 0.88, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1351', 'type': 'Property', 'age': 3.07, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1352', 'type': 'Property', 'age': 3.45, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1353', 'type': 'Property', 'age': 1.58, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1354', 'type': 'Corporate', 'age': 2.16, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1355', 'type': 'Family', 'age': 1.37, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1356', 'type': 'Civil', 'age': 3.88, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1357', 'type': 'Criminal', 'age': 4.61, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1358', 'type': 'Property', 'age': 1.6, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1359', 'type': 'Family', 'age': 2.14, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1360', 'type': 'Civil', 'age': 4.33, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1361', 'type': 'Corporate', 'age': 3.87, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1362', 'type': 'Property', 'age': 2.23, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1363', 'type': 'Property', 'age': 3.79, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1364', 'type': 'Corporate', 'age': 2.38, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1365', 'type': 'Criminal', 'age': 1.82, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1366', 'type': 'Property', 'age': 4.46, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1367', 'type': 'Property', 'age': 0.83, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1368', 'type': 'Civil', 'age': 2.65, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1369', 'type': 'Criminal', 'age': 0.69, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1370', 'type': 'Corporate', 'age': 1.18, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1371', 'type': 'Criminal', 'age': 1.96, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1372', 'type': 'Family', 'age': 2.55, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1373', 'type': 'Corporate', 'age': 3.0, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1374', 'type': 'Corporate', 'age': 4.75, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1375', 'type': 'Corporate', 'age': 1.63, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1376', 'type': 'Criminal', 'age': 1.55, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1377', 'type': 'Criminal', 'age': 3.45, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1378', 'type': 'Property', 'age': 0.58, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1379', 'type': 'Property', 'age': 3.54, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1380', 'type': 'Corporate', 'age': 1.34, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1381', 'type': 'Corporate', 'age': 1.7, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1382', 'type': 'Property', 'age': 0.66, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1383', 'type': 'Corporate', 'age': 4.97, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1384', 'type': 'Corporate', 'age': 0.76, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1385', 'type': 'Criminal', 'age': 4.81, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1386', 'type': 'Corporate', 'age': 2.31, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1387', 'type': 'Corporate', 'age': 3.33, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1388', 'type': 'Family', 'age': 3.43, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1389', 'type': 'Civil', 'age': 2.2, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1390', 'type': 'Family', 'age': 2.83, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1391', 'type': 'Family', 'age': 2.76, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1392', 'type': 'Corporate', 'age': 4.57, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1393', 'type': 'Family', 'age': 1.29, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1394', 'type': 'Corporate', 'age': 2.86, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1395', 'type': 'Corporate', 'age': 2.45, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1396', 'type': 'Corporate', 'age': 3.26, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1397', 'type': 'Property', 'age': 1.82, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1398', 'type': 'Family', 'age': 3.0, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1399', 'type': 'Civil', 'age': 2.3, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1400', 'type': 'Criminal', 'age': 2.97, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1401', 'type': 'Corporate', 'age': 4.45, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1402', 'type': 'Criminal', 'age': 4.09, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1403', 'type': 'Civil', 'age': 4.81, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1404', 'type': 'Family', 'age': 4.52, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1405', 'type': 'Property', 'age': 1.23, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1406', 'type': 'Family', 'age': 3.65, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1407', 'type': 'Civil', 'age': 3.55, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1408', 'type': 'Family', 'age': 3.65, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1409', 'type': 'Criminal', 'age': 3.68, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1410', 'type': 'Corporate', 'age': 2.58, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1411', 'type': 'Family', 'age': 3.63, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1412', 'type': 'Civil', 'age': 3.52, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1413', 'type': 'Corporate', 'age': 1.64, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1414', 'type': 'Civil', 'age': 1.84, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1415', 'type': 'Criminal', 'age': 2.28, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1416', 'type': 'Family', 'age': 3.29, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1417', 'type': 'Civil', 'age': 3.13, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1418', 'type': 'Corporate', 'age': 4.72, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1419', 'type': 'Civil', 'age': 3.41, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1420', 'type': 'Criminal', 'age': 4.63, 'adj': 9, 'lawyer': 'Available'},
{'id': 'C1421', 'type': 'Criminal', 'age': 3.37, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1422', 'type': 'Civil', 'age': 1.6, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1423', 'type': 'Corporate', 'age': 2.82, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1424', 'type': 'Property', 'age': 3.55, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1425', 'type': 'Criminal', 'age': 2.86, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1426', 'type': 'Corporate', 'age': 0.68, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1427', 'type': 'Civil', 'age': 1.88, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1428', 'type': 'Criminal', 'age': 1.18, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1429', 'type': 'Property', 'age': 0.82, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1430', 'type': 'Corporate', 'age': 1.64, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1431', 'type': 'Corporate', 'age': 4.49, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1432', 'type': 'Property', 'age': 2.2, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1433', 'type': 'Civil', 'age': 2.79, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1434', 'type': 'Family', 'age': 2.72, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1435', 'type': 'Criminal', 'age': 4.93, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1436', 'type': 'Family', 'age': 4.0, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1437', 'type': 'Property', 'age': 1.28, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1438', 'type': 'Corporate', 'age': 2.39, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1439', 'type': 'Criminal', 'age': 3.04, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1440', 'type': 'Corporate', 'age': 4.67, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1441', 'type': 'Criminal', 'age': 0.63, 'adj': 10, 'lawyer': 'Available'},
{'id': 'C1442', 'type': 'Criminal', 'age': 3.06, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1443', 'type': 'Criminal', 'age': 4.0, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1444', 'type': 'Civil', 'age': 4.79, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1445', 'type': 'Corporate', 'age': 4.68, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1446', 'type': 'Criminal', 'age': 3.26, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1447', 'type': 'Property', 'age': 3.63, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1448', 'type': 'Property', 'age': 2.56, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1449', 'type': 'Criminal', 'age': 0.67, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1450', 'type': 'Civil', 'age': 4.9, 'adj': 1, 'lawyer': 'Available'},
{'id': 'C1451', 'type': 'Corporate', 'age': 1.3, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1452', 'type': 'Corporate', 'age': 3.98, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1453', 'type': 'Criminal', 'age': 2.86, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1454', 'type': 'Family', 'age': 2.2, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1455', 'type': 'Property', 'age': 3.26, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1456', 'type': 'Corporate', 'age': 2.8, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1457', 'type': 'Corporate', 'age': 3.37, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1458', 'type': 'Corporate', 'age': 1.05, 'adj': 4, 'lawyer': 'Available'},
{'id': 'C1459', 'type': 'Family', 'age': 2.94, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1460', 'type': 'Civil', 'age': 1.62, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1461', 'type': 'Criminal', 'age': 1.2, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1462', 'type': 'Civil', 'age': 0.73, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1463', 'type': 'Corporate', 'age': 2.34, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1464', 'type': 'Property', 'age': 3.74, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1465', 'type': 'Property', 'age': 1.58, 'adj': 3, 'lawyer': 'Absent'},
{'id': 'C1466', 'type': 'Family', 'age': 0.92, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1467', 'type': 'Criminal', 'age': 2.81, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1468', 'type': 'Family', 'age': 3.79, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1469', 'type': 'Property', 'age': 1.57, 'adj': 5, 'lawyer': 'Absent'},
{'id': 'C1470', 'type': 'Family', 'age': 2.18, 'adj': 1, 'lawyer': 'Absent'},
{'id': 'C1471', 'type': 'Family', 'age': 1.14, 'adj': 0, 'lawyer': 'Absent'},
{'id': 'C1472', 'type': 'Civil', 'age': 3.28, 'adj': 5, 'lawyer': 'Available'},
{'id': 'C1473', 'type': 'Corporate', 'age': 4.93, 'adj': 4, 'lawyer': 'Absent'},
{'id': 'C1474', 'type': 'Corporate', 'age': 5.0, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1475', 'type': 'Property', 'age': 1.45, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1476', 'type': 'Criminal', 'age': 3.7, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1477', 'type': 'Family', 'age': 2.8, 'adj': 0, 'lawyer': 'Available'},
{'id': 'C1478', 'type': 'Family', 'age': 4.6, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1479', 'type': 'Property', 'age': 1.8, 'adj': 6, 'lawyer': 'Available'},
{'id': 'C1480', 'type': 'Family', 'age': 4.57, 'adj': 2, 'lawyer': 'Available'},
{'id': 'C1481', 'type': 'Property', 'age': 0.76, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1482', 'type': 'Civil', 'age': 4.54, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1483', 'type': 'Civil', 'age': 2.22, 'adj': 2, 'lawyer': 'Absent'},
{'id': 'C1484', 'type': 'Corporate', 'age': 3.42, 'adj': 8, 'lawyer': 'Absent'},
{'id': 'C1485', 'type': 'Criminal', 'age': 4.39, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1486', 'type': 'Criminal', 'age': 0.91, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1487', 'type': 'Property', 'age': 3.13, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1488', 'type': 'Civil', 'age': 1.76, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1489', 'type': 'Civil', 'age': 3.73, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1490', 'type': 'Corporate', 'age': 4.71, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1491', 'type': 'Family', 'age': 1.83, 'adj': 9, 'lawyer': 'Absent'},
{'id': 'C1492', 'type': 'Criminal', 'age': 1.52, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1493', 'type': 'Family', 'age': 2.54, 'adj': 3, 'lawyer': 'Available'},
{'id': 'C1494', 'type': 'Civil', 'age': 0.72, 'adj': 6, 'lawyer': 'Absent'},
{'id': 'C1495', 'type': 'Civil', 'age': 0.59, 'adj': 8, 'lawyer': 'Available'},
{'id': 'C1496', 'type': 'Criminal', 'age': 2.38, 'adj': 7, 'lawyer': 'Available'},
{'id': 'C1497', 'type': 'Family', 'age': 3.53, 'adj': 7, 'lawyer': 'Absent'},
{'id': 'C1498', 'type': 'Civil', 'age': 1.72, 'adj': 10, 'lawyer': 'Absent'},
{'id': 'C1499', 'type': 'Family', 'age': 0.61, 'adj': 6, 'lawyer': 'Available'},
]

cases = []
judges = {
    1: {"next_available": datetime.today()}
}

def calculate_case_age(filing_date):
    return (datetime.today() - filing_date).days

def calculate_priority(case):
    score = (
        0.4 * case['urgency'] +
        0.3 * (case['age']/30) +
        0.2 * case['adjournments']
    )
    return round(score,2)

@app.route('/')
def index():
    return render_template('index.html', cases=sample_cases)

@app.route('/add_case', methods=['POST'])
def add_case():
    data = request.json
    
    filing_date = datetime.strptime(data['filing_date'], "%Y-%m-%d")
    age = calculate_case_age(filing_date)

    case = {
        "case_id": len(cases)+1,
        "urgency": data['urgency'],
        "adjournments": data['adjournments'],
        "age": age
    }

    priority = calculate_priority(case)

    features = np.array([[age, data['urgency'], data['adjournments']]])
    delay_risk = int(model.predict(features)[0])

    hearing_date = judges[1]["next_available"] + timedelta(days=7)
    judges[1]["next_available"] = hearing_date

    case.update({
        "priority": priority,
        "delay_risk": delay_risk,
        "hearing_date": hearing_date.strftime("%Y-%m-%d")
    })

    cases.append(case)

    return jsonify(case)

@app.route('/cases', methods=['GET'])
def get_cases():
    return jsonify(cases)

if __name__ == '__main__':
    app.run(debug=True)
